### PR TITLE
Adds qmp book to our books modal

### PR DESCRIPTION
**Pull request by bh412**
At Mark's request

### CODE REVIEW

**Comment by jsharkey13** [comment]
This does work, but I really don't think that book is something we ought to be suggesting to teachers in this way. At least, it makes the maths book look much less relevant since the QMP clearly isn't relevant to much of school physics.

**Comment by bh412** [comment]
Mark requested it, perhaps you could send him the concerns?

**Comment by mw141** [comment]
Are you referring to the A level resources?
There the maths book is a core offering whereas the QMP is an extension resource.
Otherwise is there some other route to the QMP we can offer from Isaac?
M

⁣Get BlueMail for Android ​

**Comment by jsharkey13** [comment]
Think that the consensus is that it being on the A-Level page is good enough for now!

**Pull request closed without merging**
